// frontend-react/src/App.jsx
// import { useState } from 'react'
// import RegisterScreen from './components/RegisterScreen'
// import CallScreen from './components/CallScreen'

// export default function App() {
//   const [session, setSession] = useState(null) // { userId, peerId }

//   const handleRegister = (userId, peerId) => {
//     setSession({ userId, peerId })
//   }

//   const handleDisconnect = () => {
//     setSession(null)
//   }

//   if (!session) {
//     return <RegisterScreen onRegister={handleRegister} />
//   }

//   return (
//     <CallScreen
//       userId={session.userId}
//       peerId={session.peerId}
//       onDisconnect={handleDisconnect}
//     />
//   )
// }

import { useState, useEffect } from 'react'
import RegisterScreen from './components/RegisterScreen'
import CallScreen from './components/CallScreen'

export default function App() {
  const [session, setSession] = useState(null)

  // If opened from a push notification accept click, auto-populate session
  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    const userId = params.get('userId')
    const peerId = params.get('peerId')
    const action = params.get('action')
    if (userId && peerId) {
      setSession({ userId, peerId, autoAction: action || null })
    }
  }, [])

  const handleRegister = (userId, peerId) => {
    setSession({ userId, peerId, autoAction: null })
  }

  const handleDisconnect = () => {
    setSession(null)
    // Clean up URL params
    window.history.replaceState({}, '', '/')
  }

  if (!session) {
    return <RegisterScreen onRegister={handleRegister} />
  }

  return (
    <CallScreen
      userId={session.userId}
      peerId={session.peerId}
      autoAction={session.autoAction}
      onDisconnect={handleDisconnect}
    />
  )
}

// frontend-angular/src/app/app.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RegisterScreenComponent } from './components/register-screen/register-screen.component';
import { CallScreenComponent } from './components/call-screen/call-screen.component';

interface Session {
  userId: string;
  peerId: string;
  autoAction: string | null;
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RegisterScreenComponent, CallScreenComponent],
  templateUrl: './app.html',
})
export class AppComponent implements OnInit {
  session: Session | null = null;

  ngOnInit(): void {
    // If opened from a push notification accept click, auto-populate session
    const params = new URLSearchParams(window.location.search);
    const userId = params.get('userId');
    const peerId = params.get('peerId');
    const action = params.get('action');
    if (userId && peerId) {
      this.session = { userId, peerId, autoAction: action || null };
    }
  }

  handleRegister(event: { userId: string; peerId: string }): void {
    this.session = { userId: event.userId, peerId: event.peerId, autoAction: null };
  }

  handleDisconnect(): void {
    this.session = null;
    // Clean up URL params
    window.history.replaceState({}, '', '/');
  }
}
